project:
  type: website

website:
  favicon: "sihuilearns_logo_h.png"
  navbar:
    logo: "sihuilearns_logo_h.png"
    background: "#293040"
    left:
    - text: Hands-on Exercises
      menu:
        - text: Hands-on Exercise 1
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd"
        - text: Hands-on Exercise 2
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd"
        - text: Hands-on Exercise 3a
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.qmd"
        - text: Hands-on Exercise 3b
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03b.qmd"
        - text: Hands-on Exercise 4a
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04a.qmd"
        - text: Hands-on Exercise 4b
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04b.qmd"
        - text: Hands-on Exercise 4c
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04c.qmd"
        - text: Hands-on Exercise 4d
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04d.qmd"
        - text: Hands-on Exercise 5a
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05a.qmd"
        - text: Hands-on Exercise 5b
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05b.qmd"
        - text: Hands-on Exercise 5c
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05c.qmd"
        - text: Hands-on Exercise 5d
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05d.qmd"
        - text: Hands-on Exercise 5e
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05e.qmd"
        - text: Hands-on Exercise 6
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.qmd"
        - text: Hands-on Exercise 7a
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07a.qmd"
        - text: Hands-on Exercise 7b
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07b.qmd"
        - text: Hands-on Exercise 7c
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07c.qmd"
        - text: Hands-on Exercise 8
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.qmd"
        - text: Hands-on Exercise 9
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.qmd"
          
    - text: In-class Exercises
      menu:
        - text: In-class Exercise 1
          href: "In-class_Ex/In-class_Ex01/In-class_Ex01.qmd"
        - text: In-class Exercise 2
          href: "In-class_Ex/In-class_Ex02/In-class_Ex02.qmd"
        - text: In-class Exercise 3
          href: "In-class_Ex/In-class_Ex03/In-class_Ex03.qmd"
        - text: In-class Exercise 4
          href: "In-class_Ex/In-class_Ex04/In-class_Ex04.qmd"


    - text: Take-home Exercises
      menu: 
        - text: Take-home Exercise 1
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.qmd"
        - text: Take-home Exercise 2
          href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.qmd"
        - text: Take-home Exercise 3
          href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03b.qmd"
        - text: Take-home Exercise 4
          href: "Take-home_Ex/Take-home_Ex04/Take-home_Ex04a.qmd"

    - text: Extra Stuff
      menu: 
        - text: Post-Lesson Thoughts 1
          href: "Extra/Post-Lesson_01/Post-Lesson_01.qmd"
        - text: Post-Lesson Thoughts 2 (coming soon!)
    right:
      - icon: linkedin 
        href: https://www.linkedin.com/in/gohsihui/ 
        aria-label: LinkedIn


  sidebar: 
    style: "floating"
    search: true
    contents: 
      - section: "Hands-on Exercises"
        contents: 
          - Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd
          - Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd
          - Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.qmd
          - Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03b.qmd
          - Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04a.qmd
          - Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04b.qmd
          - Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04c.qmd
          - Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04d.qmd
          - Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05a.qmd
          - Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05b.qmd
          - Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05c.qmd
          - Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05d.qmd
          - Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05e.qmd
          - Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.qmd
          - Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07a.qmd
          - Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07b.qmd
          - Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07c.qmd
          - Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.qmd
          - Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.qmd
        
        
      - section: "In-class Exercises"
        contents:
          - In-class_Ex/In-class_Ex01/In-class_Ex01.qmd 
          - In-class_Ex/In-class_Ex02/In-class_Ex02.qmd 
          - In-class_Ex/In-class_Ex03/In-class_Ex03.qmd
          - In-class_Ex/In-class_Ex04/In-class_Ex04.qmd 
      - section: "Take-home Exercises"
        contents:
          - Take-home_Ex/Take-home_Ex01/Take-home_Ex01.qmd
          - Take-home_Ex/Take-home_Ex02/Take-home_Ex02.qmd
          - Take-home_Ex/Take-home_Ex03/Take-home_Ex03b.qmd
          - Take-home_Ex/Take-home_Ex04/Take-home_Ex04a.qmd
      - section: "Extra Stuff"
        contents: 
          - Extra/Post-Lesson_01/Post-Lesson_01.qmd

  page-footer:
    background: light
    left: 
      - href: https://quarto.org/
        text: "Published with Quarto |"
      - href: https://www.netlify.com/
        text: "Hosted by Netlify"

format:
  html:
    grid: 
      body-width: 1200px
      margin-width: 250px
      sidebar-width: 250px
      gutter-width: 4em
    theme: 
    - journal
    monfont: courier new
    css: styles.css
    toc: true
    toc-title: "On this page"
    number-sections: true
    toc-expand: 3
    toc-depth: 3


editor: visual

