---
title: "In-class Exercise 2"
author: "Goh Si Hui"
date: 2024/02/03
date-format: long
date-modified: "last-modified"
format: html 
execute: 
  echo: true
  eval: true
  warning: false
editor: visual 
---

Interactivity can be done via ggirafe and plotly-r. 
For ggirafe, it is an extension and it only has 3 types of interactivity functions:
1. tooltip 
2. onclick
3. dataid 

So it cannot allow us to do brushing and other types of interactivity functions. 

Need to save the ggplot as an object. then pass the object (which is a ggobj) into girafe. 
girafe save the interactivity as an svg, so it will retain the graphical resolution. 

For ggirafe, need to define the geometric, girafe, and in the geom specify the interactivity object and where it should be.

Note: can also make the scale interactive, need to select the interactive ones. 

Need to know when to use interactivity in graphs! 

Should not use bar charts to plot the average scores by race. Should show the uncertainty

function() 


Lesson 4: Fundamentals of Visual Analytics 
ggdist and ggridges: extensions of ggplot2 
ggridge and ggdist are slightly different. 
ggridge: examine the distribution 
ggdist: can visualise distribution and uncertainty, allow us to examine both distribution and uncertainty (hence the box plot)